baseURL = 'http://rse-midlands.github.io/'
languageCode = 'en-us'
title = 'RSE Midlands'
theme = "mainroad"
publishDir = "docs"

[Params.logo]
  image = "images/logo_400x400.jpg"
  title = "RSE-Midlands"
  subtitle = "A community of Research Software Engineers (RSEs) within the Midlands of England."

[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  # Enable widgets in given order
  widgets = ["social"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = false # Enable counter for each category in "Categories" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  twitter = "RSE_Midlands"
  github = "RSE-Midlands"
  linkedin = "groups/12657864"


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About Us"
    url = "/about/"
    weight = 2
  [[menu.main]]
    identifier = "News"
    name = "News"
    url = "/news/"
    weight = 2
  [[menu.main]]
    identifier = "category"
    name = "Events"
    weight = 3
  [[menu.main]]
    identifier = "category1"
    name = "8th June 2022"
    url = "/event-8th-June"
    parent = "category"
    weight = 1
# https://codingnconcepts.com/hugo/nested-menu-hugo/
